# -*- coding: utf-8 -*-
"""stress.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19V90uC57wz0RAnjFu_5mdnDndClutVcf
"""

!pip install librosa scikit-learn joblib nltk SpeechRecognition pydub

import os
import zipfile
import numpy as np
import librosa
import joblib
import nltk
import speech_recognition as sr

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from nltk.sentiment import SentimentIntensityAnalyzer

nltk.download('vader_lexicon')

from google.colab import drive
drive.mount('/content/drive')

DATA_PATH = "/content/drive/MyDrive/Stress detection/data/ravdess"

def emotion_to_stress(emotion_code):
    stressed = ['05', '06', '07']  # angry, fear, disgust
    return 1 if emotion_code in stressed else 0


def extract_audio_features(file_path):
    y, sr = librosa.load(file_path, duration=5)

    mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=13)
    mfcc_mean = np.mean(mfcc.T, axis=0)

    zcr = np.mean(librosa.feature.zero_crossing_rate(y=y))
    rms = np.mean(librosa.feature.rms(y=y))

    return np.hstack([mfcc_mean, zcr, rms])


# 👇 OUTSIDE the previous function (important)
def speech_to_text(file_path):
    recognizer = sr.Recognizer()

    try:
        with sr.AudioFile(file_path) as source:
            audio = recognizer.record(source)

        text = recognizer.recognize_google(audio)
    except:
        text = ""

    return text

sia = SentimentIntensityAnalyzer()

def extract_text_features(text):
    scores = sia.polarity_scores(text)

    return np.array([
        scores['neg'],
        scores['neu'],
        scores['pos'],
        scores['compound']
    ])

def combine_features(file_path):
    audio_features = extract_audio_features(file_path)

    text = speech_to_text(file_path)
    text_features = extract_text_features(text)

    combined = np.hstack([audio_features, text_features])

    return combined

def load_dataset():
    X = []
    y = []

    print("Processing dataset...")

    for actor in os.listdir(DATA_PATH):
        actor_path = os.path.join(DATA_PATH, actor)

        if os.path.isdir(actor_path):
            for file in os.listdir(actor_path):
                if file.endswith(".wav"):
                    file_path = os.path.join(actor_path, file)

                    emotion_code = file.split("-")[2]
                    label = emotion_to_stress(emotion_code)

                    features = combine_features(file_path)

                    X.append(features)
                    y.append(label)

    return np.array(X), np.array(y)

X, y = load_dataset()

print("Dataset shape:", X.shape)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = RandomForestClassifier(n_estimators=100)
model.fit(X_train, y_train)

accuracy = model.score(X_test, y_test)
print("Accuracy:", accuracy)

joblib.dump(model, "multimodal_stress_model.pkl")

def predict_stress(file_path):
    features = combine_features(file_path)
    features = features.reshape(1, -1)

    prediction = model.predict(features)[0]

    text = speech_to_text(file_path)

    result = "Stressed" if prediction == 1 else "Not Stressed"

    return result, text

sample_file = None

for actor in os.listdir(DATA_PATH):
    actor_path = os.path.join(DATA_PATH, actor)
    for file in os.listdir(actor_path):
        if file.endswith(".wav"):
            sample_file = os.path.join(actor_path, file)
            break
    if sample_file:
        break

result, text = predict_stress(sample_file)

print("\n--- TEST RESULT ---")
print("Audio File:", sample_file)
print("Recognized Text:", text)
print("Stress Prediction:", result)

import gradio as gr

# Wrapper function for Gradio
def gradio_predict(audio_file):
    if audio_file is None:
        return "No file uploaded", ""

    result, text = predict_stress(audio_file)

    return result, text


# Create UI
interface = gr.Interface(
    fn=gradio_predict,
    inputs=gr.Audio(type="filepath", label="Upload Audio File"),
    outputs=[
        gr.Textbox(label="Stress Prediction"),
        gr.Textbox(label="Recognized Speech")
    ],
    title="🎧 Multimodal Stress Detection System",
    description="Upload a speech audio file to detect stress using voice + text sentiment analysis.",
    examples=None,
    theme="soft"
)

# Launch app
interface.launch(share=True)